### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by oktomus**

### CODE REVIEW

**Comment by jwindgassen** [comment]
tyvm

**Comment by jwindgassen** [comment]
I moved/created a page with examples in the wiki. But thank you for the initial impulse (otherwise I probably would not have done it in the near future 😅)

**Comment by oktomus** [comment]
Cool! 

I have two questions regarding the wiki:
- Can we convert a YAML into a struct? Or is it possible to add this feature? That would be so useful!
- In the **Creating a YAML File** section, you mention we can't have mixed types in BP, but the result snippet just after shows mixed types. Maybe would be clearer to put that bellow C++ and show something else for BP?

Thanks again!

**Comment by jwindgassen** [comment]
1) I'm not 100% sure what you mean by that, but I think you want to parse a YAML into a struct without needing to explicitly create all the `USTRUCT(...)` Structs before that, right?
These Structs work via a `UStructProperty` instance that will be automatically generated by the UHT when building. While I think it might be possible to create such an instance on the fly and then parse the YAML into it, I don't think it would prove as useful:
YAML Nodes are inherently untyped and yaml-cpp will try to convert them when you query the Node for a specific type. So the `UStructProperty` generated at runtime would have no way of determining the type of values.

2) I moved the sections around a bit. I will update the Blueprint Screenshots anyway as soon as I have implemented the corresponding features

**Comment by oktomus** [comment]
> you want to parse a YAML into a struct without needing to explicitly create all the USTRUCT(...) Structs before that, right?

No the `USTRUCT` would be already created, I meant add a BP function that takes a YAML path or node and populate a struct of any type using the YAML data. Like "Populate from struct" but reversed.

**Comment by jwindgassen** [comment]
This is what `ParseNodeIntoStruct` does (both for Blueprints and C++). The reverse direction, creating a YAML from the contents of a Struct, is not possible yet.
(I can see, however, that a name like `FillStructFromYamlNode` of `PopulateStructWithYamlNode` might have been a better name)

**Comment by oktomus** [comment]
> is not possible yet

Ah too bad :( And do you know why ?

**Comment by jwindgassen** [comment]
Just haven't come around to implementing it yet. The other direction was required in another project, so I prioritized it. But it should be somewhat straight forward. You basically need to recreate/copy the methods in `UYamlParsing`, but alter them, so they convert a Struct to a YAML

**Pull request merged**
