### PR TITLE
Const Iterator

### PR DESCRIPTION
**Pull request by Cleroth**
cf. #6

### CODE REVIEW

**Comment by jwindgassen** [comment]
tyvm. 

I think I might replace the classes by plain a typedef in the future, I don't think there is a need for these custom classes (anymore). But this LGTM for now 😃

**Comment by Cleroth** [comment]
Right, templating it would definitely be better, this was just the easiest way.

**Comment by Cleroth** [comment]
In hindsight, it probably should've been called FYamlConstIterator

**Comment by jwindgassen** [comment]
I originally refrained from templating, as that voids Blueprint compatibility. But that was before I moved all Blueprint Functions to the Function Libraries. So I think we should be good by now.

We can just leave it at that for now, I will think about it when I got some spare time.

**Pull request merged**
